backend:
  name: git-gateway # <--- CHANGEMENT CRUCIAL : Netlify gère l'authentification pour vous
  branch: main # Assurez-vous que c'est le nom de votre branche principale (main ou master)

# Le répertoire où les articles de blog seront enregistrés
media_folder: "_posts/images"
public_folder: "/assets/images"

# Définition des champs du Blog/Dossiers
collections:
  - name: "blog" # Nom interne du contenu
    label: "Dossiers & Actualités"
    folder: "_posts" # Le dossier où Jekyll cherche les articles
    create: true # Permet de créer de nouveaux articles
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string", required: true}
      - {label: "Auteur", name: "author", widget: "string", default: "Vertic'Albâtre"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Corps de l'article", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}